CREATE TABLE IF NOT EXISTS visitas_programadas (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    codigo VARCHAR(32) NOT NULL,
    casa_id INT UNSIGNED NOT NULL,
    nombre_visitante VARCHAR(150) NOT NULL,
    telefono VARCHAR(25) NULL,
    placas VARCHAR(25) NULL,
    identificacion VARCHAR(100) NULL,
    autorizado_por VARCHAR(180) NOT NULL,
    tipo ENUM('FAMILIAR','AMISTAD','PROVEEDOR','SERVICIO','REPARTIDOR','OTRO') NOT NULL DEFAULT 'FAMILIAR',
    fecha_programada DATE NOT NULL,
    hora_programada TIME NULL,
    vigencia_hasta DATETIME NULL,
    estatus ENUM('PROGRAMADA','EN_CURSO','FINALIZADA','CANCELADA') NOT NULL DEFAULT 'PROGRAMADA',
    notas TEXT NULL,
    fecha_entrada DATETIME NULL,
    fecha_salida DATETIME NULL,
    creado_por_usuario_id BIGINT UNSIGNED NULL,
    entrada_por_usuario_id BIGINT UNSIGNED NULL,
    salida_por_usuario_id BIGINT UNSIGNED NULL,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_visitas_codigo (codigo),
    INDEX idx_visitas_casa_fecha (casa_id, fecha_programada),
    INDEX idx_visitas_estatus_fecha (estatus, fecha_programada),
    CONSTRAINT fk_visitas_casa FOREIGN KEY (casa_id) REFERENCES direcciones(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_visitas_creador FOREIGN KEY (creado_por_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_visitas_entrada_usuario FOREIGN KEY (entrada_por_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_visitas_salida_usuario FOREIGN KEY (salida_por_usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
